[config]
schemaVersion = "0.1.2"

[package]
namespace = "deB"
name = "Debby_Peam"
versionNumber = "0.1.2"
description = "Adds content!"
websiteUrl = "https://github.com/TheDebbyCase/DebbyPeam"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
PEAKModding-PEAKLib_Items = "1.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "."

[[build.copy]]
source = "./DebbyPeam/Builds/Release/netstandard2.1/DebbyPeam.dll"
target = "BepInEx/plugins/DebbyPeam/DebbyPeam.dll"

[[build.copy]]
source = "./DebbyPeam/Builds/debbypeam"
target = "BepInEx/plugins/DebbyPeam/debbypeam"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
communities = ["peak"]
[publish.categories]
repo = ["mods", "misc", "items"]


